import "./styles/design.scss";
// import 'bootstrap';
// import "owl.carousel";
// import "@fancyapps/fancybox";
// import "lightgallery";
// import "lg-zoom";
// import "lg-share";
// import "daterangepicker";
// import "../node_modules/daterangepicker/daterangepicker.css";
// import '../node_modules/animate.sass/scss/animate.scss';
// import { CountUp } from "countup.js";
// import "./scripts/libraries";
// import "./scripts/header";
// import "./scripts/modals";
//import "./scripts/imageViewer";
// import "./scripts/youtubeModal";
// import "./scripts/modals";
// import "./scripts/customChart";
// import "./scripts/daterangepicker";
// import "./scripts/formValidations";
import "./scripts/modules/authmodule";
import "./scripts/commons/snackbacks";
import "./scripts/commons/animations";
import "./scripts/forms/forms-groups";
import "./scripts/main";
import "./pug/components/register/registerModal";
